### ISSUE TITLE
Developing pause screen

### ISSUE THREAD

**Issue by manners99** [Stacked-Success/Softeng310#102]
# Developing puase screen

## Summary
*Add further options to the user when the screen is paused*

## Description
*Defintly adding options to return to the home screen or start a new game. Potentially adding a reference to the settings page, or atleast giving the iser some control of some of the setting such as music voume from within the game*

## Completion Criteria
*Minimum requirement are for the user to be able to restart and leave the game from within the pause screen with a appropriate test suite*

**Comment by shyke0611** [comment]
Looks good

**Comment by srab017** [comment]
Approved
