### ISSUE TITLE
Unwanted tracking of Controls.txt

### ISSUE THREAD

**Issue by sdes755** [Stacked-Success/Softeng310#118]
## Description
This issue is to fix the unwanted tracking of the controls.txt file which is unique to every user, hence should not be tracked.

## Expected Behaviour
Controls.txt should not be tracked, and only modified locally.

## Actual Behaviour
Controls.txt is tracked due to prior commit

## Steps to Reproduce
Run the game, change keybinds.

## Images and Resources
N/A

## Environment
*Operating System:* MacOS/Windows
*Device:* Laptop/PC
*Browser:* N/A

**Comment by Shubh250** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
