### ISSUE TITLE
Tutorial screen always appearing before a new game

### ISSUE THREAD

**Issue by manners99** [Stacked-Success/Softeng310#121]
# Tutorial Screen Always Showing
## Expected Behaviour
Screen should only appear if the user has not yet viewed it 

## Actual Behaviour
Screen appears every time the game iis played. Will not appear if the user opens the tutorial manually before that game

## Steps to Reproduce
Play one game, return to main menu, and then start a new game

**Comment by shyke0611** [comment]
Approved
