### ISSUE TITLE
HOLD and NEXT piece png images currently have white borders + slightly off centered

### ISSUE THREAD

**Issue by mche791** [Stacked-Success/Softeng310#57]
![hold and next piece bug](https://github.com/user-attachments/assets/70c36ed4-0d1e-46c4-93e9-e6a2d8c18dde)

**Comment by axu732** [comment]
To add to this, it seems the next piece is not loading anymore.

**Comment by axu732** [comment]
Likely what you can do is set the size of the image view smaller or make the images of the pieces smaller when being loaded in.

**Comment by quaidsage** [comment]
Hold and Preview images are now inaccurate to current tetrimino visuals.
