### ISSUE TITLE
Create Points Shop 

### ISSUE THREAD

**Issue by shyke0611** [Stacked-Success/Softeng310#86]
Develop a Points Shop feature for the Tetris game. The shop will allow players to spend points earned during gameplay on various items, such as:

Different Tetrimino art styles (e.g., colors, patterns).
Special effects (e.g., visual effects triggered when clearing lines).
Unlockable content such as custom backgrounds or soundtracks.

**Comment by sdes755** [comment]
Approved

**Comment by manners99** [comment]
Approved
