### ISSUE TITLE
Create Instructions Menu

### ISSUE THREAD

**Issue by sdes755** [Stacked-Success/Softeng310#90]
Create an Instructions menu for the Tetris game. Here, the user will be given instructions on playing the game and changing it to their desired settings.

Provides the user with:
Types of game modes.
The objective of each game mode.
Game mechanics and controls.
Visuals on what each control/movement does to a tetromino.
Tips and strategies.

**Comment by manners99** [comment]
Game mechanics and controlls are taught in the tutorial, otherwise all looks good. Could this be done by addapting the current tutorial? Or would some of it be better of on the home screen? Otherwise approved

**Comment by shyke0611** [comment]
Approved
