### ISSUE TITLE
Final touches and linking final version to readme

### ISSUE THREAD

**Issue by sdes755** [Stacked-Success/Softeng310#91]
## Description

This issue involves completing the final touches on the project and ensuring that the final version is correctly linked in the README file. This includes:

- Ensuring that the documentation is up-to-date and that all recent changes are reflected in the README.
- Linking the final, stable version of the project, including a clear description of features and how to use the project.
- Adding any additional instructions for setting up and running the project locally or on a server.
- Ensuring the project is fully functional and free of any known critical bugs before marking it as a "Final Version."

**Comment by manners99** [comment]
Good idea, approved

**Comment by shyke0611** [comment]
approved
