### ISSUE TITLE
Marathon Mode

### ISSUE THREAD

**Issue by srab017** [Stacked-Success/Softeng310#99]
#Marathon Mode

## Summary
Implement a new Marathon Mode in the falling blocks game, where the player must survive for as long as possible by clearing a target number of blocks while managing increasing speed and difficulty.

## Description
In Marathon Mode, the objective is to clear a predefined number of lines (e.g., 100 lines) as quickly as possible. Unlike Endless Mode, which continues indefinitely, this mode challenges the player to reach the goal in the shortest time while maintaining control over the falling blocks.

## Requirements

- Add Marathon Mode to the game mode selection in the main menu.
- Implement mechanics to track line clears and display the target (e.g., “Lines Cleared: 45/100”).
- Implement a progressively increasing speed for falling blocks, making the game more difficult as the player clears more lines.
- Display the time elapsed during gameplay.
- Add a scoring system that rewards players based on:
    - Time taken to reach the target.
    - Line clearing efficiency (e.g., clearing multiple lines at once).
- Ensure the game ends when either:
    - The player clears the required number of lines.
    - The stack of blocks reaches the top of the screen.

## Completion Criteria
- The player can complete a game of Marathon Mode by clearing a set number of lines.
- The game tracks the number of lines cleared and displays this information to the player.
- The difficulty increases as the game progresses (e.g., blocks fall faster or are more complex).
- The game ends appropriately when the target is reached or when the stack of blocks reaches the top.
- The final score reflects the time taken and efficiency in clearing lines.
- Marathon Mode is fully integrated into the main menu and functions smoothly without major bugs or gameplay interruptions.

**Comment by shyke0611** [comment]
Approved

**Comment by sdes755** [comment]
Approved
